### ISSUE TITLE
配合k8s使用gosip+ZLMediaKit的时候，大概是怎么样一个场景需求？

### ISSUE THREAD

**Issue by ganttee** [panjjo/gosip#1]
你好，请问：
1.配合k8s部署使用gosip+ZLMediaKit的时候，大概是怎么样一个场景需求？
2.protoc文件好像没有上传，make的时候报错了

**Comment by panjjo** [comment]
![image](https://user-images.githubusercontent.com/4423200/103143803-d1f32880-4758-11eb-93b5-35ed820fc27c.png)
gosip做为信令服务，负责和摄像头录像机之间的通讯（设备注册，保活，设备信息，请求直播/回放等 GB28181相关操作）
ZLMediaKit是媒体服务器，主要负责接受视频流转码转协议。

**Comment by panjjo** [comment]
protoc的去掉了，没有用micro grpc。用的restfulapi
