### ISSUE TITLE
支持级联吗？

### ISSUE THREAD

**Issue by wangdemon** [panjjo/gosip#11]
首先感谢大佬，通过大佬将sip服务器升级2.0后，我通过本地模拟客户端连接成功了。
客户端如下图：
![微信截图_20220922143317](https://user-images.githubusercontent.com/20681339/191674928-ca4a0e6a-edaa-41eb-a35d-3150c4605a9f.jpg)
播放效果：
![2022-09-22 14-32-18 的屏幕截图](https://user-images.githubusercontent.com/20681339/191675025-ce37a265-086f-4743-859f-9cc67396d184.png)
感谢大佬的无私帮助。
最后请问一下大佬，gosip支持级联吗？

**Comment by panjjo** [comment]
目前不支持，级联在开发中。

**Comment by wangdemon** [comment]
好的，感谢大佬的无私奉献！
