### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by wangdemon** [panjjo/gosip#8]
ZLMediaKit和gosip都已经编译运行，但是，我不知道他们怎么结合起来使用。
(1) 我想在局域网内，搭建一个自己的gb28181推流，拉流的系统。
(2) 使用ZLMediaKit做流媒体的服务器，使用自己USB摄像头，或者使用本地的视频文件，通过ffmpeg推流摄像头或者本地视频。
(3) 使用另一台电脑查看视频流内容。
上述3条需要，怎才能实现

**Comment by panjjo** [comment]
不好意思，gosip仅支持GB28181的接入，不支持本地文件和usb摄像头推流。如果想要实现这两个功能建议直接使用zlm就可以。

**Comment by panjjo** [comment]
节后我重新整理一下接口和文档。到时候就容易看了。

**Comment by wangdemon** [comment]
好的，感谢博主大大

**Comment by wangdemon** [comment]
我通过本地程序模拟，注册失败。
![图像 1](https://user-images.githubusercontent.com/20681339/190044837-1da372c3-4333-498b-9633-2fc06d8832a6.jpg)

**Comment by wangdemon** [comment]
这是抓包情况
![图像2](https://user-images.githubusercontent.com/20681339/190045013-fab60227-8aa0-4e31-8e81-91f63106ab95.jpg)

**Comment by wangdemon** [comment]
这是本地程序信息
![图像3](https://user-images.githubusercontent.com/20681339/190046826-734ef932-ab5c-4923-9cdc-2d0d2f0bb8f3.jpg)

**Comment by panjjo** [comment]
我更新了一下，加上了在线api接口，修复了几个bug，你在试试看。
